services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 40
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG_RETENTION_HOURS: 12
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_BYTES: 1073741824
    user: "0:0"
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - main-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - main-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vodokanal_db
      POSTGRES_USER: vodokanal_user
      POSTGRES_PASSWORD: vodokanal_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vodokanal_user -d vodokanal_db" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - main-network

  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim-moscow
    ports:
      - "8001:8080"
    environment:
      - PBF_URL=file:///local_pbf/Moscow.osm.pbf
      - NOMINATIM_THREADS=4
      - SHARED_MEM=4
    volumes:
      - ./:/local_pbf:ro
    shm_size: '4g'
    restart: unless-stopped
    networks:
      - main-network
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8085:8080"
    networks:
      - main-network
 
volumes:
  kafka-data:
  postgres-data:

networks:
  main-network:
    external: true
