services:
  external-data-consumer:
    image: external-data-consumer:latest
    restart: "no"
    ports:
      - "8081:8081"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    labels:
      amplicode.image: springboot
    networks:
      - main-network

  itp-data-processing:
    image: itp-data-processing:latest
    restart: "no"
    ports:
      - "8082:8082"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8082/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - NOMINATIM_URL=http://nominatim-moscow:8080
    labels:
      amplicode.image: springboot
    networks:
      - main-network

  vodokanal-data-service:
    image: vodokanal-data-service:latest
    restart: "no"
    ports:
      - "8083:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    labels:
      amplicode.image: springboot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vodokanal_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ITP_DATA_PROCESSING_URL=http://itp-data-processing:8082
    networks:
      - main-network

networks:
  main-network:
    external: true
