spring:
  application:
    name: itp-data-processing

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: itp-data-processing-group
      properties:
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        connections.max.idle.ms: 540000
        num.consumer.fetchers: 20
    listener:
      concurrency: 20

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info

logging:
  level:
    ru.bluewater: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  kafka:
    topic:
      input: external-itp-data
      output: processed-itp-data

nominatim:
  url: http://localhost:8001
