spring:
  application:
    name: vodokanal-data-service

  threads:
    virtual:
      enabled: true

  jackson:
    time-zone: Europe/Samara

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: vodokanal-data-consumer-group
      properties:
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        connections.max.idle.ms: 540000
        num.consumer.fetchers: 20
    listener:
      concurrency: 20

  datasource:
    url: jdbc:postgresql://localhost:5432/vodokanal_db
    username: ${DB_USERNAME:vodokanal_user}
    password: ${DB_PASSWORD:vodokanal_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  enable-data-rest: false

app:
  kafka:
    topic:
      input: processed-itp-data
      accidents: predicted-itp-accidents

itp-data-processing:
  url: http://localhost:8082