spring:
  application:
    name: vodokanal-data-service

  threads:
    virtual:
      enabled: true

  task:
    execution:
      pool:
        virtual-threads: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: itp-data-consumer-group
      properties:
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        connections.max.idle.ms: 540000
        num.consumer.fetchers: 20
      listener:
        concurrency: 20

  datasource:
    url: jdbc:postgresql://localhost:5432/vodokanal_db
    username: ${DB_USERNAME:vodokanal_user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,kafka

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  enable-data-rest: false
